name: export-solution
# Export solution from DEV environment ny tolling dev

on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the "main" branch     
  pull_request:
    branches: [ "main" ] 
      
  
env:
#edit your values here
  ENVIRONMENT_URL: 'https://nytolling-azbasedev.crm.dynamics.com/'
  solution_name: crm_test_solution

permissions:
  contents: write
jobs:
  export-from-dev:
    runs-on: ubuntu-latest
    # or you can say runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{secrets.CLIENT_ID}}
        client-secret: ${{ secrets.CLIENT_SECRETID }}
        tenant-id: ${{secrets.TENANT_ID}}


    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{secrets.CLIENT_ID}}
        client-secret: ${{ secrets.CLIENT_SECRETID }}
        tenant-id: ${{secrets.TENANT_ID}}
        solution-name: ${{ env.solution_name }}
        solution-output-file: ${{ github.event.repository.name}}/${{ env.solution_name }}_unmanaged.zip
        overwrite: true
        
    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: ${{ github.event.repository.name}}/${{ env.solution_name }}_unmanaged.zip
        solution-folder: ${{ github.event.repository.name}}/${{ env.solution_name }}
        solution-type: 'Unmanaged'
        overwrite-files: true
        
    - name: Commit changes
      run: |
            git fetch --all
            git config --global user.email "nallandula.kirankumar@conduent.com"
            git config --global user.name "kirankumar159"
            git checkout main
            git add --all 
            git commit -m "Updates from the dev environment"
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            git push       


            
            
