name: import-solution
# Import solution to TEST environment

on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the "main" branch     
  pull_request:
    branches: [ "main" ] 
      
  
env:
#edit your values here
  ENVIRONMENT_URL: 'https://ctsgtolling-test.crm.dynamics.com/'
  solution_name: cicddemo

permissions:
  contents: write
jobs:
  import-to-test:
    runs-on: ubuntu-latest
    # or you can say runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

        
    - name: Pack solution
      uses: microsoft/powerplatform-actions/pack-solution@v0
      with:
        solution-folder: ${{ github.event.repository.name}}/${{ env.solution_name }}
        solution-file: ${{ github.event.repository.name}}/${{ env.solution_name }}_unmanaged.zip
        solution-type: Unmanaged

    - name: Import solution to test env
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: ${{ env.ENVIRONMENT_URL }}
        app-id: ${{secrets.CLIENT_ID}}
        client-secret: ${{ secrets.CLIENT_SECRETID }}
        tenant-id: ${{secrets.TENANT_ID}}
        solution-file: ${{ github.event.repository.name}}/${{ env.solution_name }}_unmanaged.zip
        force-overwrite: true
        publish-changes: true
       
    